# -*- coding: utf-8 -*-
"""Titanic_task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LC1CQB5cJkuXToXTpJ3Qd4pZ6J-xrIA8
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import matplotlib.pyplot as plt
import seaborn as sns

titanic = pd.read_csv('/content/Titanic dataset.csv')

titanic.head()

np.shape(titanic)

titanic.describe(include='all')

"""
The output data types are both Quantitative and Qualitative"""



tit_na = titanic.isna()
tit_na.sum().sum()

titanic.duplicated(keep=False).sum().sum()

"""No duplicated values"""

def find_outliers_IQR(df):

   q1=df.quantile(0.25)

   q3=df.quantile(0.75)

   IQR=q3-q1

   outliers = df[((df<(q1-1.5*IQR)) | (df>(q3+1.5*IQR)))]

   return outliers

outliers = find_outliers_IQR(titanic)
outliers.sum()

sns.countplot(x='Sex', data=titanic)

"""Males are more than femals"""

sns.countplot(x='Survived', data=titanic)

sns.countplot(x='Sex', data=titanic, hue='Survived', palette='viridis')

"""Females that had survived is more than males"""

sns.lineplot(x=	'PassengerId',y='Age', data=titanic)



sns.countplot(x='Pclass', data=titanic, hue='Survived', palette='viridis')

sns.countplot(x='Pclass', data=titanic, hue='Sex', palette='viridis')

"""Most men are in Pclass-3"""

sns.lineplot(x='Age', y='Survived', data=titanic).set(xlabel='X axis- Age', ylabel='Y axis - Survived', title='Line plot - Age vs. Survived')

sns.boxplot(x='Age', data=titanic, color='red')

sns.jointplot(x='Age',y='Survived', data=titanic,hue='Sex')

"""Most people survived are at age ranging from 20:40 years most of them are women"""

sns.jointplot(x='Pclass',y='Survived', data=titanic,hue='Sex')

"""most of people in pclass 3 are males"""

